language: node_js
node_js:
  - 'stable'

branches:
  only:
    - master

cache:
  yarn: true

env:
  global:
    # GH_TOKEN
    - secure: "oIGMI5tlN3Ck4Vnc5wCKGAR/lKWaV0lKCZz/ui/cjzDmqVt/Ie8ThpEZm4nKj/IvCOlBbWPAjUfStyostSDnYrF6JAmthDH4hh7kxbGlRSlb+fJSu1vKJq9XOUGHtgxtyybUgcLGTKraHOM7zBzsW8lbh9+g4QxqgbaWXD7nq/o="

deploy:
  - provider: script
    skip_cleanup: true
    script: publish.sh
    on:
      branch: master
