#!/bin/bash

# Do not publish for pull requests
if [[ "$TRAVIS_PULL_REQUEST" == "true" ]]; then
	echo "Building docs only for commits on master branch!"
	exit 0
fi

PAGES_REPO="tmp"
mkdir $PAGES_REPO

git clone -v https://github.com/avaly/url-cycle.git $PAGES_REPO
cd $PAGES_REPO

git config credential.helper "store --file=.git/credentials"
echo "https://$GH_TOKEN:@github.com" > .git/credentials
git config user.name "Travis-CI"
git config user.email "travis@travis-ci.com"

git checkout gh-pages
git merge --ff-only master
git push origin gh-pages
